[Definition]
failregex = ^<HOST> - .* "(?:GET|POST|HEAD) .*" 429 .*$
            ^.*limiting requests, excess: .* by zone "(?:evac_html|evac_home|evac_ad|evac_scan)", client: <HOST>,.*$
            ^.*limiting connections by zone "evac_conn", client: <HOST>,.*$
ignoreregex =
