[Definition]
failregex = ^<HOST> - .* "(?:GET|POST|HEAD) .*" 429 .*$
            ^<HOST> - .* "(?:GET|POST|HEAD) .*" 403 .*bad_paid_click="1".*$
            ^<HOST> - .* "(?:GET|POST|HEAD) .*" 403 .*blocked_automation_ua="1".*$
            ^.*limiting requests, excess: .* by zone "(?:evdn_html|evdn_home|evdn_ad)", client: <HOST>,.*$
            ^.*limiting connections by zone "evdn_conn", client: <HOST>,.*$
ignoreregex =
